name = "godingtalk-worker"
main = "src/index.ts"
compatibility_date = "2026-03-15"
workers_dev = true

[vars]
CORS_ALLOW_ORIGIN = "*"
GITHUB_REPOSITORY = "zhzx2026/DingTalkGoGoGo"
GITHUB_WORKFLOW_FILE = "remote-runner.yml"
GITHUB_LOGIN_WORKFLOW_FILE = "windows-login.yml"
GITHUB_REF = "main"
ALLOW_PUBLIC_REGISTRATION = "true"

[[d1_databases]]
binding = "DB"
database_name = "godingtalk-db"
database_id = "12f5efa5-c6f4-4ac9-9089-620818102c5b"

[[r2_buckets]]
binding = "FILES"
bucket_name = "godingtalk-files"
preview_bucket_name = "godingtalk-files-preview"

[triggers]
crons = ["*/15 * * * *"]
